In [4]:
import numpy as np
a = np.random.randint(10 , size = (4,4))
a

array([[9, 8, 2, 2],
       [4, 2, 7, 8],
       [5, 1, 7, 4],
       [8, 0, 5, 4]])

In [12]:
import numpy as np
x = np.linspace(9, 49, dtype = int)
for elem in x:
    print(elem,end=' ')

9 9 10 11 12 13 13 14 15 16 17 17 18 19 20 21 22 22 23 24 25 26 26 27 28 29 30 31 31 32 33 34 35 35 36 37 38 39 40 40 41 42 43 44 44 45 46 47 48 49 

In [15]:
import numpy as np
b = np.eye(5,6)
b

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [21]:
import numpy as np
x = np.linspace(0, 5, 10 ,endpoint = False)
for elem in x:
    print(round(elem,2),end=' \n')

0.0 
0.5 
1.0 
1.5 
2.0 
2.5 
3.0 
3.5 
4.0 
4.5 


In [28]:
import numpy as np
x = np.linspace(0, 5, 10 ,endpoint = False, startpoint = False)
for elem in x:
    print(round(elem,2),end=' \n')

TypeError: _linspace_dispatcher() got an unexpected keyword argument 'startpoint'

In [29]:
import numpy as np
x = np.linspace(0, 5, 10 ,endpoint = False)
for elem in x:
    if elem == 0 or elem ==5:
        continue
    print(round(elem,2),end=' \n')

0.5 
1.0 
1.5 
2.0 
2.5 
3.0 
3.5 
4.0 
4.5 


In [30]:
import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)

In [32]:
input_

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [62]:
input_1= (input_[2:3 , 0:3])
for x in input_1:
    print(*x, end =" ")
    print()
input_2= (input_[1:4 , 3:4])
for x in input_2:
    print(*x, end =" ")
print()
input_3= (input_[2:4 , 0:5])
for x in input_3:
    print(*x, end =" ")
    print()
input_4= (input_[1:3 , 1:3])
for x in input_4:
    print(*x, end =" ")

11 12 13 
9 14 19 
11 12 13 14 15 
16 17 18 19 20 
7 8 12 13 

In [69]:
# Problem Statemnt:
# Find indices of non-zero elements from the array [1,2,0,0,4,0] ?
# Print the index of non-zero elements.
# Output Format :
# index1 index2 index3 ... 
import numpy as np
a = [1,2,0,0,4,0] 
b = np.array(a)
print(b.argmin())


2


In [76]:
import numpy as np
a = [1,2,0,0,4,0] 
b = np.array(a)
ind = np.where(b == 0)
#print(*ind)
for elem in ind:
    print(*elem,end=' ')

2 3 5 

In [77]:


import numpy as np
a = [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]
b = np.array(a)
ind = np.where(b%3==0)
#print(*ind)
for elem in ind:
    print(*elem,end=' ')


1 4 7 

In [82]:
import numpy as np
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
b = np.array(a)
# ind = np.where(b%2==0)
#print(*ind)
for elem in b:
    if (elem%2==0)  :
        print(elem, end = " ")

2 4 6 8 10 

In [84]:
import numpy as np
a = [-1, 2, -1, 4, -1, 6, -1, 8, -1, 10]
b = np.array(a)
for elem in b:
    print(elem,end=' ')

-1 2 -1 4 -1 6 -1 8 -1 10 

In [88]:
import numpy as np
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
b = np.array(a)
# ind = np.where(b%2==0)
#print(*ind)
for elem in b:
    print(elem , end=" ")
    if (elem%2!=0)  :
        print(-1, end = " ")

1 -1 2 3 -1 4 5 -1 6 7 -1 8 9 -1 10 

In [89]:
import numpy as np
nparray=np.arange(1,11,1)
nparray[nparray%2!=0]=-1
for i in nparray: 
    print(i,end=' ')

-1 2 -1 4 -1 6 -1 8 -1 10 

In [95]:
import numpy as np
a = [11, 2, 13, 4, 15, 6, 27, 8, 19]
b = np.array(a)
b[b.argmax()]= 0
for elem in b:
    print(elem,end=' ')

# print(b.max())
# print(b.argmax())

11 2 13 4 15 6 0 8 19 

In [98]:
import numpy as np
a = [1, 2, -3, -4, -5, -6, -7, -8, 9, 10]
b = np.array(a)
for elem in b:
    print(elem,end=' ')

1 2 -3 -4 -5 -6 -7 -8 9 10 

In [99]:
import numpy as np
a = [1, 2, -3, -4, -5, -6, -7, -8, 9, 10]
b = np.array(a)
for elem in b:
    if ()
    print(elem,end=' ')

SyntaxError: invalid syntax (<ipython-input-99-4d1c5d3edca8>, line 5)

In [107]:
import numpy as np
age= np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height= np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])

for elem in age, height:
    if age[]
    print(*elem,end=' \n')

[15 17 19 20 14 21 16 19 13 20 22 23 21 16 18 19 20 15 17 18]
15 17 19 20 14 21 16 19 13 20 22 23 21 16 18 19 20 15 17 18 
156 144 180 162 152 157 154 155 151 150 158 179 126 182 183 154 159 160 172 149 


In [7]:
import numpy as np
a = np.array ([[21, 20, 19, 18, 17],[16, 15, 14, 13, 12], [11, 10,  9,  8,  7],[ 6,  5,  4,  3,  2]])

In [8]:
a

array([[21, 20, 19, 18, 17],
       [16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7],
       [ 6,  5,  4,  3,  2]])

In [9]:
a.sort(axis=0)

In [10]:
a

array([[ 6,  5,  4,  3,  2],
       [11, 10,  9,  8,  7],
       [16, 15, 14, 13, 12],
       [21, 20, 19, 18, 17]])

In [12]:
import numpy as np
a = np.array ([[21, 20, 19, 18, 17],[16, 15, 14, 13, 12], [11, 10,  9,  8,  7],[ 6,  5,  4,  3,  2]])
a.sort(axis=0)
print(a)

[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]
