In [3]:
import numpy as np

a = np.array(['t', 'b', 'r', 'd', 'e', 'f', 'z', 'a'])
b = np.random.randint(1, 20, 8)

print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[19  3  4 17 13 17  9 19]


In [4]:
print(b > 10)

[ True False False  True  True  True False  True]


In [5]:
bool_arr = b > 10
print(bool_arr)
new_arr = b[bool_arr]
print(new_arr)

[ True False False  True  True  True False  True]
[19 17 13 17 19]


In [6]:
new_arr = b[b > 10]
new_arr

array([19, 17, 13, 17, 19])

In [7]:
new_arr = b[(b > 10) & (b < 18)]
new_arr

array([17, 13, 17])

In [8]:
print(b)
c = b
c

[19  3  4 17 13 17  9 19]


array([19,  3,  4, 17, 13, 17,  9, 19])

In [9]:
c[:3] = 19
print(c)
c[c > 15] = 100
c

[19 19 19 17 13 17  9 19]


array([100, 100, 100, 100,  13, 100,   9, 100])

In [10]:
print(b)


[100 100 100 100  13 100   9 100]


In [11]:
print(b[b == 100])

[100 100 100 100 100 100]


In [12]:
ind = np.where(b == 100)
ind

(array([0, 1, 2, 3, 5, 7], dtype=int64),)

In [15]:
print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[100 100 100 100  13 100   9 100]


In [18]:
ind = np.where(b == 100)
print(*ind , *a[ind])

[0 1 2 3 5 7] t b r d f a
