In [2]:
import numpy as np

a = [1, 2, 3]
b = np.array(a)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
a = [1, 2, 3, '5', 4.5]
b = np.array(a, dtype = str)
print(b)

['1' '2' '3' '5' '4.5']


In [4]:
a = [1, 2, 3, '5', 4.5]
b = np.array(a * 3)
print(b)

['1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5']


In [5]:
b = np.ones(3, dtype = int)
b

array([1, 1, 1])

In [6]:
b = np.ones((2, 3), dtype = int)
b

array([[1, 1, 1],
       [1, 1, 1]])

In [7]:
b = np.zeros(3, dtype = int)
b

array([0, 0, 0])

In [8]:
b = np.zeros((3, 4))
b

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [9]:
b = np.full((3, 3), 5, dtype = float)
b

array([[ 5.,  5.,  5.],
       [ 5.,  5.,  5.],
       [ 5.,  5.,  5.]])

In [10]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
b = np.arange(2, 10)
b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
b = np.arange(2, 20, 2)
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [3]:
import numpy as np
b = np.linspace(2, 10)
b
# print(b[1] - b[0])
# print(b[3] - b[2])

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [33]:
b = np.linspace(2, 10, 5, dtype = int, endpoint = False)
b

array([2, 3, 5, 6, 8])

In [34]:
b = np.identity(3)
b

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [36]:
b = np.eye(3, 4)
b

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.]])

In [61]:
b = np.random.rand(3)
b

array([ 0.26949561,  0.06503371,  0.29373579])

In [66]:
b = np.random.rand(10)*10
b

array([ 9.49183749,  8.36951039,  6.19188291,  9.82127093,  6.97574587,
        4.00180958,  4.79949638,  6.74820971,  6.62471485,  8.77169984])

In [62]:
b = np.random.rand(2, 3)
b

array([[ 0.82563547,  0.6411471 ,  0.75633672],
       [ 0.73608608,  0.49069966,  0.72339434]])